[package]
name = "liana"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6"
eframe = "0.35.0"
egui-probe = { version = "0.12.0", features = ["derive"] }
egui_commonmark = "0.24"
image = { version = "0.25", default-features = false, features = ["png"] }
indoc = "2.0.7"
rig = "0.40.0"
rig-memory = "0.40.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["macros","rt-multi-thread"] }
